// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkbtkbfnxtzxhupcqsdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYnRrYmZueHR6eGh1cGNxc2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzAyNTEsImV4cCI6MjA3MTk0NjI1MX0.qy2-3E56Jk-6HL2jNBNci4sBYQM9LxS3-yeLR8q3MwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});